version: "3.9"

services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: kfMsxhug4zo0VHBrIhq0bPirUMlPdoc5pED_O0Go_uRyKc63cRy9p5V9pkGRj2oUIlI
    env_file: .env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8000:8000"
  postgres:
    environment:
      POSTGRES_PASSWORD: Amir1343
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"

volumes:
  postgres-data:

