# Generated by Django 2.2.24 on 2021-09-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210927_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
