# Generated by Django 2.2.24 on 2021-10-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210929_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='group_chat',
            field=models.BooleanField(default=False),
        ),
    ]
