# Generated by Django 2.2.24 on 2021-10-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_chatgroup_group_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='mimetype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
