# Generated by Django 2.2.24 on 2021-10-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211021_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('away', 'Away'), ('online', 'Online')], default='online', max_length=6),
        ),
    ]
