# Generated by Django 2.2.24 on 2021-10-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211027_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Away', 'Away'), ('Online', 'Online')], default='online', max_length=6),
        ),
    ]
