# Generated by Django 2.2.24 on 2022-01-21 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20211102_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='users.ChatGroup')),
            ],
        ),
    ]
