# Generated by Django 2.2.24 on 2022-01-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220121_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
